micronaut.application.name = 'walletd'

# network-id must specify a valid org.bitcoinj.base.BitcoinNetwork either by
# a lowercase name ("mainnet", "testnet", "signet", or "regtest") or by
# an ID ("org.bitcoin.production", "org.bitcoin.testnet", etc.)
walletd.config.network-id = "regtest"

# The server port for listening for JSON-RPC and REST queries
walletd.config.server-port = 8080

# path to wallet data-directory, if `null`, defaults to AppDataDirectory for appName
#walletd.config.data-dir

# Base name for wallet files, e.g. walletd-mainnet.wallet, walletd-mainnet.spvchain
walletd.config.wallet-base-name = "walletd"
